/*--Borrar tabla
Drop Table LIB_EDITORIAL_TB;
Drop sequence LIB_EDITORIAL_TB_SQ;
*/
--Crear tabla registro de editoriales en una librería
CREATE TABLE LIB_EDITORIAL_TB (	
    "EDITORIAL_ID" NUMBER(15,0) NOT NULL ENABLE,   
    "NAME" VARCHAR2(150 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"CORRESPONDENCE_ADDRESS" VARCHAR2(120 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"PHONE_NUMBER" VARCHAR(20 BYTE)  DEFAULT ' ' NOT NULL ENABLE,
	"MAXIMUN_BOOKS_REGISTERED" NUMBER(15,0) DEFAULT -1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"EMAIL" VARCHAR(50 BYTE)  DEFAULT NULL,
    CONSTRAINT "LIB_EDITORIAL_PK" PRIMARY KEY ("EDITORIAL_ID")
    USING INDEX (CREATE UNIQUE INDEX LIB_EDITORIAL_IND_PK ON LIB_EDITORIAL_TB ("EDITORIAL_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255)  ENABLE
);
/
CREATE SEQUENCE LIB_EDITORIAL_SQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER;
/
CREATE OR REPLACE EDITIONABLE TRIGGER LIB_EDITORIAL_TR
    BEFORE INSERT ON LIB_EDITORIAL_TB FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.EDITORIAL_ID IS NULL THEN 
            SELECT LIB_EDITORIAL_SQ.NEXTVAL INTO :NEW.EDITORIAL_ID FROM DUAL;
        END IF; 
    END IF; 
END;
/
ALTER TRIGGER LIB_EDITORIAL_TR ENABLE;
/
CREATE INDEX LIB_EDITORIAL_IND_NAME ON POR_CLARO_REQUEST_TB ("NAME")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS;
/
COMMENT ON COLUMN "LIB_EDITORIAL_TB"."EDITORIAL_ID" IS 'Identificador Autoincremental Unico PK';
COMMENT ON COLUMN "LIB_EDITORIAL_TB"."NAME" IS 'Nombre de la editorial';
COMMENT ON COLUMN "LIB_EDITORIAL_TB"."CORRESPONDENCE_ADDRESS" IS 'Direccion de correspondecia de la editorial';
COMMENT ON COLUMN "LIB_EDITORIAL_TB"."PHONE_NUMBER" IS 'Numero de telefono de la editorial';
COMMENT ON COLUMN "LIB_EDITORIAL_TB"."MAXIMUN_BOOKS_REGISTERED" IS 'Numero maximo de libros que se pueden registrar -1 indica sin limite';
COMMENT ON COLUMN "LIB_EDITORIAL_TB"."CREATED_AT" IS 'Fecha en que se realizo el registro';
COMMENT ON COLUMN "LIB_EDITORIAL_TB"."UPDATED_AT" IS 'Fecha en que se realizo modificacion del registro';
COMMENT ON COLUMN "LIB_EDITORIAL_TB"."EMAIL" IS 'Correo electronico de la editorial';
COMMENT ON TABLE "LIB_EDITORIAL_TB"  IS 'Tabla contiene registro de las editoriales';
/
/*--Borrar tabla
Drop Table POR_REGULATORY_REQUEST_TB;
Drop sequence POR_REGULATORY_REQUEST_SQ;
*/
--Crear tabla registro del estado de una solicitud de portabilidad
CREATE TABLE POR_REGULATORY_REQUEST_TB (	
	"REGULATORY_REQUEST_ID" NUMBER(15,0) DEFAULT 0 NOT NULL ENABLE,
	"CLARO_REQUEST_ID" NUMBER(15,0) DEFAULT 0 NOT NULL ENABLE,
	"STATUS" VARCHAR(20 BYTE)  DEFAULT ' ' NOT NULL ENABLE,
	"CONDITION" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATION_USER" VARCHAR2(60 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(60 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "POR_REGULATORY_REQUEST_PK" PRIMARY KEY ("REGULATORY_REQUEST_ID")
    USING INDEX (CREATE UNIQUE INDEX POR_REGULATORY_REQUEST_IND_PK ON POR_REGULATORY_REQUEST_TB ("REGULATORY_REQUEST_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "TBL_PORTA_ALT_IX" )  ENABLE
) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "TBL_PORTA_ALT_DT" ;
/
CREATE SEQUENCE POR_REGULATORY_REQUEST_SQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;
/
CREATE OR REPLACE EDITIONABLE TRIGGER POR_REGULATORY_REQUEST_TR
    BEFORE INSERT ON POR_REGULATORY_REQUEST_TB FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.REGULATORY_REQUEST_ID IS NULL THEN 
            SELECT POR_REGULATORY_REQUEST_SQ.NEXTVAL INTO :NEW.REGULATORY_REQUEST_ID FROM DUAL;
        END IF; 
    END IF; 
END;
/
ALTER TRIGGER POR_REGULATORY_REQUEST_TR ENABLE;
/
ALTER TABLE POR_REGULATORY_REQUEST_TB ADD CONSTRAINT FK_CLARO_REQUEST_ID FOREIGN KEY (CLARO_REQUEST_ID) REFERENCES POR_CLARO_REQUEST_TB (CLARO_REQUEST_ID);
/
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_REQUEST_TB"."REGULATORY_REQUEST_ID" IS 'Identificador Autoincremental Unico PK';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_REQUEST_TB"."CLARO_REQUEST_ID" IS 'Llave forenea de la entidad solicitud de portabilidad';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_REQUEST_TB"."STATUS" IS 'Estado de la una solicitud de portabilidad';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_REQUEST_TB"."CONDITION" IS 'Estado del registro 1 activo, 0 inactivo';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_REQUEST_TB"."CREATION_USER" IS 'Usuario quien realizo el registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_REQUEST_TB"."CREATED_AT" IS 'Fecha en que se realizo el registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_REQUEST_TB"."UPDATE_USER" IS 'Usuario quien realizo la modificacion del registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_REQUEST_TB"."UPDATED_AT" IS 'Fecha en que se realizo modificacion del regsitro';
COMMENT ON TABLE "PORTABILIDAD_SCHEME"."POR_REGULATORY_REQUEST_TB"  IS 'Tabla contiene registro del estado de una solicitude de portabilidad';
/
/*--Borrar tabla
Drop Table POR_ATTACHED_DOCUMENTS_TB;
Drop sequence POR_ATTACHED_DOCUMENTS_SQ;
*/
--Crear tabla registro del documentos asociados una solicitud de portabilidad
CREATE TABLE POR_ATTACHED_DOCUMENTS_TB (
	"ATTACHED_DOCUMENT_ID" NUMBER(15,0) DEFAULT 0 NOT NULL ENABLE,
	"CLARO_REQUEST_ID" NUMBER(15,0) DEFAULT 0 NOT NULL ENABLE,
	"DOCUMENT_NAME" VARCHAR(200 BYTE)  DEFAULT ' ' NOT NULL ENABLE,
	"DOCUMENT_TYPE" VARCHAR(50 BYTE)  DEFAULT ' ' NOT NULL ENABLE,
	"URM_URL" VARCHAR(200 BYTE)  DEFAULT ' ' NOT NULL ENABLE,
	"UCM_URL" VARCHAR(200 BYTE)  DEFAULT ' ' NOT NULL ENABLE,
	"CONDITION" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATION_USER" VARCHAR2(60 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(60 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "POR_ATTACHED_DOCUMENTS_PK" PRIMARY KEY ("ATTACHED_DOCUMENT_ID")
    USING INDEX (CREATE UNIQUE INDEX POR_ATTACHED_DOCUMENTS_IND_PK ON POR_ATTACHED_DOCUMENTS_TB ("ATTACHED_DOCUMENT_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "TBL_PORTA_MED_IX" )  ENABLE
) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "TBL_PORTA_MED_DT" ;
/
CREATE SEQUENCE POR_ATTACHED_DOCUMENTS_SQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;
/
CREATE OR REPLACE EDITIONABLE TRIGGER POR_ATTACHED_DOCUMENTS_TR
    BEFORE INSERT ON POR_ATTACHED_DOCUMENTS_TB FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ATTACHED_DOCUMENT_ID IS NULL THEN 
            SELECT POR_ATTACHED_DOCUMENTS_SQ.NEXTVAL INTO :NEW.ATTACHED_DOCUMENT_ID FROM DUAL;
        END IF; 
    END IF; 
END;
/
ALTER TRIGGER POR_ATTACHED_DOCUMENTS_TR ENABLE;
/
ALTER TABLE POR_ATTACHED_DOCUMENTS_TB ADD CONSTRAINT FK_CLARO_REQUEST_ID1 FOREIGN KEY (CLARO_REQUEST_ID) REFERENCES POR_CLARO_REQUEST_TB (CLARO_REQUEST_ID);
/
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."ATTACHED_DOCUMENT_ID" IS 'Identificador Autoincremental Unico PK';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."CLARO_REQUEST_ID" IS 'Llave forenea de la entidad solicitud de portabilidad';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."DOCUMENT_NAME" IS 'Nombre del documento';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."DOCUMENT_TYPE" IS 'Tipo de documento';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."URM_URL" IS 'Url de URM';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."UCM_URL" IS 'Url de UCM';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."CONDITION" IS 'Estado del registro 1 activo, 0 inactivo';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."CREATION_USER" IS 'Usuario quien realizo el registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."CREATED_AT" IS 'Fecha en que se realizo el registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."UPDATE_USER" IS 'Usuario quien realizo la modificacion del registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"."UPDATED_AT" IS 'Fecha en que se realizo modificacion del regsitro';
COMMENT ON TABLE "PORTABILIDAD_SCHEME"."POR_ATTACHED_DOCUMENTS_TB"  IS 'Tabla contiene registro de los documentos asociados a una solicitude de portabilidad';
/
/*--Borrar tabla
Drop Table POR_NUMBERS_REG_REQ_TB;
Drop sequence POR_NUMBERS_REG_REQ_SQ;
*/
--Crear tabla registro de numeros asociados una solicitud de portabilidad
CREATE TABLE POR_NUMBERS_REG_REQ_TB (
	"NUMBERS_REG_REQ_ID" NUMBER(15,0) DEFAULT 0 NOT NULL ENABLE,
	"REGULATORY_REQUEST_ID" NUMBER(15,0) DEFAULT 0 NOT NULL ENABLE,
	"NUMBER" VARCHAR(10 BYTE)  DEFAULT ' ' NOT NULL ENABLE,
	"CONDITION" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATION_USER" VARCHAR2(60 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(60 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "POR_NUMBERS_REG_REQ_PK" PRIMARY KEY ("NUMBERS_REG_REQ_ID")
    USING INDEX (CREATE UNIQUE INDEX POR_NUMBERS_REG_REQ_IND_PK ON POR_NUMBERS_REG_REQ_TB ("NUMBERS_REG_REQ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "TBL_PORTA_MED_IX" )  ENABLE
) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "TBL_PORTA_MED_DT" ;
/
CREATE SEQUENCE POR_NUMBERS_REG_REQ_SQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;
/
CREATE OR REPLACE EDITIONABLE TRIGGER POR_ATTACHED_DOCUMENTS_TR
    BEFORE INSERT ON POR_NUMBERS_REG_REQ_TB FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.NUMBERS_REG_REQ_ID IS NULL THEN 
            SELECT POR_NUMBERS_REG_REQ_SQ.NEXTVAL INTO :NEW.NUMBERS_REG_REQ_ID FROM DUAL;
        END IF; 
    END IF; 
END;
/
ALTER TRIGGER POR_NUMBERS_REG_REQ_TR ENABLE;
/
ALTER TABLE POR_NUMBERS_REG_REQ_TB ADD CONSTRAINT FK_REGULATORY_REQUEST_ID FOREIGN KEY (REGULATORY_REQUEST_ID) REFERENCES POR_REGULATORY_REQUEST_TB (REGULATORY_REQUEST_ID);
/
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_NUMBERS_REG_REQ_TB"."NUMBERS_REG_REQ_ID" IS 'Identificador Autoincremental Unico PK';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_NUMBERS_REG_REQ_TB"."REGULATORY_REQUEST_ID" IS 'Llave forenea de la entidad request de portabilidad';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_NUMBERS_REG_REQ_TB"."NUMBER" IS 'Numero de celular asociado';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_NUMBERS_REG_REQ_TB"."CONDITION" IS 'Estado del registro 1 activo, 0 inactivo';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_NUMBERS_REG_REQ_TB"."CREATION_USER" IS 'Usuario quien realizo el registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_NUMBERS_REG_REQ_TB"."CREATED_AT" IS 'Fecha en que se realizo el registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_NUMBERS_REG_REQ_TB"."UPDATE_USER" IS 'Usuario quien realizo la modificacion del registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_NUMBERS_REG_REQ_TB"."UPDATED_AT" IS 'Fecha en que se realizo modificacion del regsitro';
COMMENT ON TABLE "PORTABILIDAD_SCHEME"."POR_NUMBERS_REG_REQ_TB"  IS 'Tabla contiene registro de los numeros asociados a una solicitude de portabilidad';
/
/*--Borrar tabla
Drop Table POR_REGULATORY_MESSAGES_TB;
Drop sequence POR_REGULATORY_MESSAGES_SQ;
*/
--Crear tabla registro de mensajes xml asociados una solicitud de portabilidad
CREATE TABLE POR_REGULATORY_MESSAGES_TB (
	"REGULATORY_MESSAGE_ID" NUMBER(15,0) DEFAULT 0 NOT NULL ENABLE,
	"REGULATORY_REQUEST_ID" NUMBER(15,0) DEFAULT 0 NOT NULL ENABLE,
	"TRANSACTION_ID" VARCHAR(20 BYTE)  DEFAULT ' ' NOT NULL ENABLE,
	"PROCCESS_ID" VARCHAR(20 BYTE)  DEFAULT ' ' NOT NULL ENABLE,
	"OBSERVATIONS" VARCHAR2(4000 BYTE) DEFAULT NULL,
	"DONOR_OPERATOR" VARCHAR2(10 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"MESSAGE_TYPE" VARCHAR2(20 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"XML_REQUEST" CLOB DEFAULT ' ',
	"CONDITION" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATION_USER" VARCHAR2(60 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(60 BYTE) DEFAULT ' ' NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
    CONSTRAINT "POR_REGULATORY_MESSAGES_PK" PRIMARY KEY ("REGULATORY_MESSAGE_ID")
    USING INDEX (CREATE UNIQUE INDEX POR_REGULATORY_MESSAGES_IND_PK ON POR_REGULATORY_MESSAGES_TB ("REGULATORY_MESSAGE_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "TBL_PORTA_ALT_IX" )  ENABLE
) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "TBL_PORTA_ALT_DT" ;
/
CREATE SEQUENCE POR_REGULATORY_MESSAGES_SQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION;
/
CREATE OR REPLACE EDITIONABLE TRIGGER POR_REGULATORY_MESSAGES_TR
    BEFORE INSERT ON POR_REGULATORY_MESSAGES_TB FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.REGULATORY_MESSAGE_ID IS NULL THEN 
            SELECT POR_REGULATORY_MESSAGES_SQ.NEXTVAL INTO :NEW.REGULATORY_MESSAGE_ID FROM DUAL;
        END IF; 
    END IF; 
END;
/
ALTER TRIGGER POR_REGULATORY_MESSAGES_TR ENABLE;
/
ALTER TABLE POR_REGULATORY_MESSAGES_TB ADD CONSTRAINT FK_REGULATORY_REQUEST_ID1 FOREIGN KEY (REGULATORY_REQUEST_ID) REFERENCES POR_REGULATORY_REQUEST_TB (REGULATORY_REQUEST_ID);
/
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."REGULATORY_MESSAGE_ID" IS 'Identificador Autoincremental Unico PK';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."REGULATORY_REQUEST_ID" IS 'Llave forenea de la entidad request de portabilidad';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."TRANSACTION_ID" IS 'Numero de celular asociado';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."PROCCESS_ID" IS 'Numero de celular asociado';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."OBSERVATIONS" IS 'Numero de celular asociado';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."DONOR_OPERATOR" IS 'Numero de celular asociado';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."MESSAGE_TYPE" IS 'Numero de celular asociado';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."XML_REQUEST" IS 'Numero de celular asociado';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."CONDITION" IS 'Estado del registro 1 activo, 0 inactivo';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."CREATION_USER" IS 'Usuario quien realizo el registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."CREATED_AT" IS 'Fecha en que se realizo el registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."UPDATE_USER" IS 'Usuario quien realizo la modificacion del registro';
COMMENT ON COLUMN "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"."UPDATED_AT" IS 'Fecha en que se realizo modificacion del regsitro';
COMMENT ON TABLE "PORTABILIDAD_SCHEME"."POR_REGULATORY_MESSAGES_TB"  IS 'Tabla contiene registro de los numeros asociados a una solicitude de portabilidad';
/