server:
        port: 8084
spring:
################### DataSource Configuration ##########################
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        password: napo123
        url: jdbc:oracle:thin:@localhost:1525:xe
        username: desarrollo
    jpa:
        hibernate:
# Hibernate ddl auto (create, create-drop, validate, update)
            ddl-auto: validate
        open-in-view: false
#        properties:
#            hibernate:
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#                dialect: org.hibernate.dialect.Oracle12cDialec